### ISSUE TITLE
error messages codes

### ISSUE THREAD

**Issue by MoonshineSG** [gnea/grbl-Mega#14]
what happened to the error descriptions ? in the previous versions the error messages (and the settings) has nice explanations, now it's all gone... :(

**Comment by chamnit** [comment]
@MoonshineSG : I thought I had a FAQ answer for this, but I guess not. It was removed because of the flash limits of the 328p. It was either the human-readable messages or overrides/laser mode. Not both. I may bring it back in the Mega version soon, but it's not a priority. GUIs have been instructed to supply this information for the user. There is a set of CSV files in the repo for them to parse and keep updated from.

**Comment by MoonshineSG** [comment]
Thanks for pointing to the cvs files. it helps.
