### ISSUE TITLE
error 26 for full circles

### ISSUE THREAD

**Issue by barma1ey** [gnea/grbl-Mega#31]
HI!
Grbl gcode parser returns an error in case G2/G3 command has all axis words omitted. For example, "G3J10". It is quite strange behavior, since circles with no helix don't require those values at all. Only offset values are obligatory to calculate radius and center. Correct me if I'm wrong

**Comment by chamnit** [comment]
Depends on which gcode standard is being used. Grbl's arc implementation was first written to the NIST gcode standard, which mandates that at least one axis word in the arc plane must be included. The LinuxCNC standard allows no axis words to be passed and interprets missing axis words as a full circle. Relatively recently, Grbl started to move over to the LinuxCNC, so I suppose I should update it. Since it's not critical, I'll note this in the supported gcodes in the wiki., and will update this in the next major version. I generally don't like to change how things operate in major releases unless they are critical.
